config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "user_registration"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope 'orders' do
    post 'add_item_to_cart', to: 'orders#add_item_to_cart'
    get 'cart', to: 'orders#cart'
    get 'minicart', to: 'orders#minicart'
    post 'checkout', to: 'orders#checkout'
    get 'checkout_completed', to: 'orders#checkout_completed'
    get ':id', to: 'orders#show'
  end
  
  get 'user', to: 'users#show'
  
  resources :products
  
  resources :categories
 
  #comments routes
  resources :comments do
    collection do
      get 'for_product/:product_id', to: 'comments#for_product'
    end
  end
  
  
  resources :rates
 
 root 'home#index'
 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :product
 belongs_to :user
 
 scope :for_product, ->(product_id) { where(product_id: product_id) }
 
 def to_json
  {id: self.id, comment: self.comment, first_name: self.user.first_name, last_name: self.user.last_name}
 end
end

app/models/image.rb
class Image < ApplicationRecord
  
  belongs_to :product

  has_attached_file :img, styles: { large: "500x500", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  
  #attr_accessible :image, :image_file_name
end

app/models/order.rb
class Order < ApplicationRecord
  
  enum status: [ :cart, :payment, :making, :to_deliver, :delivering, :delivered ]

  before_save :update_total_value
  
  belongs_to :user
  has_many :order_items
  
  scope :waiting_payment, -> { where(status: 'payment') }
  scope :making, -> { where(status: 'making') }
  scope :to_deliver, -> { where(status: 'to_deliver') }
  scope :delivered, -> { where(status: 'delivering') }
  
  def update_total_value
    self.order_items.each { |i| i.value = i.product.price }
    self.total_value = self.order_items.inject(0) { |sum,i| sum + (i.value * i.quantity) }
  end
  
  def add_item(product_id, quantity)
    product = Product.find(product_id)
    order_item = OrderItem.new(value: product.price, quantity: quantity, product: product)
    self.order_items << order_item
    order_item
  end
  
  def status_to_human
    I18n.t("activerecord.attributes.order.status.#{status}")
  end
  
  def created_at_to_human
    created_at.strftime("%d/%m/%Y")
  end
  
  def user_name
    user.full_name
  end
  
  def status_to_user
    return I18n.t("activerecord.attributes.order.status.making") if status == 'to_deliver'
    I18n.t("activerecord.attributes.order.status.#{status}")
  end
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :images
  has_many :comments
  has_many :rates
  
  accepts_nested_attributes_for :images, :allow_destroy => true
  
  def rate_average
    rates.average(:rate)
  end
  
  def main_image(image_format = :medium)
    return 'http://placekitten.com/50/50' if images.empty?
    images.first.img.url(image_format)
  end
  
  def images_url
    images.map{
     |i|
      ind = i.img.url(:large).index('?')
      i.img.url(:large)[0,ind]
    }
    
    #['/system/images/imgs/000/000/008/medium/mulher.jpg','/system/images/imgs/000/000/009/medium/bike.jpg','/system/images/imgs/000/000/010/medium/caminho.jpg']
  end
  
end

app/models/rate.rb
class Rate < ApplicationRecord
 belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
           
    has_many :orders
    has_many :comments
    
    validates :first_name, presence: true
    
    def get_cart
      order = self.orders.where( status: 'cart' ).first
      order.nil? ? self.orders.new( status: 'cart' ) : order
    end
    
    def full_name
      "#{first_name} #{last_name}"
    end
       
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
     #index, show, new, edit, create, update and destroy
    
    def index
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    #index, show, new, edit, create, update and destroy
    
    def index
        @product = Product.find_by_id(13)
        byebug
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
  end
  
  def cart
    @order = current_user.orders.find_by_status('cart')
  end
  
  def add_item_to_cart 
    order = current_user.get_cart
    order.add_item(params[:orders][:product_id], params[:orders][:quantity])
    order.save
  end
  
  def minicart
    @order = current_user.orders.find_by_status('cart')
    render layout: false
  end
  
  def checkout
    @order = current_user.orders.find_by_status('cart')
    @order.payment!
    @order.address = params[:order][:address]
    @order.save
    OrderMailer.payment(@order).deliver_later
    redirect_to checkout_completed_path
  end
  
  def checkout_completed
    @order = current_user.orders.last
  end
  
private

  def order_params
    
  end
  
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

  def create
    rate = Rate.new
    rate.rate = params[:rate][:rate]
    rate.product_id = params[:rate][:product_id]
    rate.save
    
    render :json => Product.find(rate.product_id).rate_average
  end

  def update
  end
  
private
  
  def rates_params
    params.require(:rate).permit(:autor, :rate)
  end
  
  def find_commentable
    resource, id = request.path.split('/')[1,2]
    @rateable = resource.singularize.classify.constantize.find(id)
  end
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = SecureRandom.hex(6)
    end

    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: uid, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: { 
          target: uid, 
          slide_to: index
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }

      content_tag(:div, image_tag(image), options)
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end

    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/_add_item.html.erb
<div class="row">
  <div class="add-item-form">
    <%= form_for :orders, url: add_item_to_cart_path, :html => {class: 'add-to-cart-form'} do |f| %>
      <%= f.hidden_field :product_id, { value: @product.id } %>
      <%= f.number_field :quantity, { value: 1 } %>
      <button type="submit" class="btn btn-primary"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
    <% end %>
  </div>
  <div class="add-item-confirmation" style="display:none;">
    <%= @product.name %> foi adicionado no seu carrinho
  </div>
</div>

app/views/orders/_cart_list.html.erb
<div class="cart_list">
  <table class="table table-condensed table-hover">
    <tr>
      <th>Produto</th>
      <th>Imagem</th>
      <th>Valor</th>
      <th>Quantidade</th>
    </tr>
    <tbody>
      <% @order.order_items.each do |i| %>
        <tr>
          <th><%= i.product.name %></th>
          <th><%= image_tag i.product.main_image(:thumb) %></th>
          <th><%= i.value %></th>
          <th><%= i.quantity %></th>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <th></th>
      <th></th>
      <th>Valor total</th>
      <th><%= @order.total_value %></th>
    </tfoot>
  </table>
</div>

app/views/orders/_checkout_form.html.erb
<%= form_for @order, url: checkout_path, :method => "post"  do |cart| %>
  Endereço de entrega: <br/>
  <%= cart.text_area :address, { value: @order.user.address } %><br>
  <%= cart.submit "Finalizar compra" %>
<% end %>

app/views/orders/cart.html.erb
<% if @order.present? %>
    <%= render 'cart_list' %>
    <%= render 'checkout_form' %>
<% else %>
  <h2>Seu carrinho esta vazio</h2>
<% end %>

app/views/orders/checkout_completed.html.erb
<div class="checkoutCompleted">
  <%= render "cart_list" %>
  <h3><%= current_user.first_name %>, você receberá um e-mail na conta <%= current_user.email %> com informações para pagamento.
  Obrigado!
  </h3>
</div>

app/views/orders/minicart.html.erb
<div class="minicart">
  <div class="close-button" align="right">
    <a href="#" class="fa fa-times" id="close" aria-hidden="true"></a>
  </div>
  <div class="product-list">
    <% @order.order_items.each do |item| %>
      <div class="row">
        <div class="col-md-2"><%= image_tag item.product.main_image(:thumb) %></div>
        <div class="col-md-6"><%= item.product.name %></div>
        <div class="col-md-1"><%= item.quantity %></div>
        <div class="col-md-3"><%= item.value %></div>
      </div>
    <% end %>
  </div>
  <div class="total-value">
    Total: R$ <%= @order.total_value %>
  </div>
  <div class="go-to-cart">
    <%= link_to 'Ir para o carrinho', cart_path, class: 'btn btn-primary' %>
  </div>
</div>

    

app/views/orders/show.html.erb
<h2>Pedido número <%= @order.id %></h2>

<%= render 'cart_list' %>