config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "user_registration"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope 'orders' do
    post 'add_item_to_cart', to: 'orders#add_item_to_cart'
    get 'cart', to: 'orders#cart'
    get 'minicart', to: 'orders#minicart'
    post 'checkout', to: 'orders#checkout'
    get 'checkout_completed', to: 'orders#checkout_completed'
    get ':id', to: 'orders#show'
  end
  
  get 'user', to: 'users#show'
  
  resources :products
  
  resources :categories
 
  #comments routes
  resources :comments do
    collection do
      get 'for_product/:product_id', to: 'comments#for_product'
    end
  end
  
  
  resources :rates
 
 root 'home#index'
 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :product
 belongs_to :user
 
 scope :for_product, ->(product_id) { where(product_id: product_id) }
 
 def to_json
  {id: self.id, comment: self.comment, first_name: self.user.first_name, last_name: self.user.last_name}
 end
end

app/models/image.rb
class Image < ApplicationRecord
  
  belongs_to :product

  has_attached_file :img, styles: { large: "500x500", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  
  #attr_accessible :image, :image_file_name
end

app/models/order.rb
class Order < ApplicationRecord
  
  enum status: [ :cart, :payment, :making, :to_deliver, :delivering, :delivered ]

  before_save :update_total_value
  
  belongs_to :user
  has_many :order_items
  
  scope :waiting_payment, -> { where(status: 'payment') }
  scope :making, -> { where(status: 'making') }
  scope :to_deliver, -> { where(status: 'to_deliver') }
  scope :delivered, -> { where(status: 'delivering') }
  
  def update_total_value
    self.order_items.each { |i| i.value = i.product.price }
    self.total_value = self.order_items.inject(0) { |sum,i| sum + (i.value * i.quantity) }
  end
  
  def add_item(product_id, quantity)
    product = Product.find(product_id)
    order_item = OrderItem.new(value: product.price, quantity: quantity, product: product)
    self.order_items << order_item
    order_item
  end
  
  def status_to_human
    I18n.t("activerecord.attributes.order.status.#{status}")
  end
  
  def created_at_to_human
    created_at.strftime("%d/%m/%Y")
  end
  
  def user_name
    user.full_name
  end
  
  def status_to_user
    return I18n.t("activerecord.attributes.order.status.making") if status == 'to_deliver'
    I18n.t("activerecord.attributes.order.status.#{status}")
  end
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :images
  has_many :comments
  has_many :rates
  
  accepts_nested_attributes_for :images, :allow_destroy => true
  
  def rate_average
    rates.average(:rate)
  end
  
  def main_image(image_format = :medium)
    return 'http://placekitten.com/50/50' if images.empty?
    images.first.img.url(image_format)
  end
  
  def images_url
    images.map{
     |i|
      ind = i.img.url(:large).index('?')
      i.img.url(:large)[0,ind]
    }
    
    #['/system/images/imgs/000/000/008/medium/mulher.jpg','/system/images/imgs/000/000/009/medium/bike.jpg','/system/images/imgs/000/000/010/medium/caminho.jpg']
  end
  
end

app/models/rate.rb
class Rate < ApplicationRecord
 belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
           
    has_many :orders
    has_many :comments
    
    validates :first_name, presence: true
    
    def get_cart
      order = self.orders.where( status: 'cart' ).first
      order.nil? ? self.orders.new( status: 'cart' ) : order
    end
    
    def full_name
      "#{first_name} #{last_name}"
    end
       
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    #index, show, new, edit, create, update and destroy
    
    def index
        @product = Product.find_by_id(13)
        byebug
    end
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = SecureRandom.hex(6)
    end

    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: uid, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: { 
          target: uid, 
          slide_to: index
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }

      content_tag(:div, image_tag(image), options)
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end

    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commons/_index_list.html.erb
<% @thing.each do |l|%>

<div class="col-md-4">
    <p>
    <div class="row">
        <strong><%= l.name %></strong>
    </div>
    <div class="row">
        <% im = l.images.first %>
        <%= image_tag im.img.url(:medium) %>
    </div>
    <div class="row">
        <strong>Preço: </strong>
        <%= l.price %>
    </div>
    <%= link_to 'detalhes', l %>
    </p>
</div>

<% end %>

app/views/commons/_item.html.erb
<div class="row">
<strong><%= @item.name %></strong>
</div>

<div class="row">
  <p>
   <% @item.images.each do |i| %>
   <div class="col-md-4">
   <%= image_tag i.img.url(:medium) %>
   </div>
   <% end %>
  </p>
</div>

<div class="row">
  <strong>Descrição:</strong> <%= @item.description%> 
</div>

<div class="row">
  <div class="col-md-3 col-md-offset-9">
    <strong>Preço:</strong> $<%= @item.price %>
  </div>
</div>

app/views/lamps/_lamps_list.html.erb
<% @lamp.each do |l|%>

<div class="col-md-4">
    <p>
    <div class="row">
        <strong><%= l.name %></strong>
    </div>
    <div class="row">
        foto
    </div>
    <div class="row">
        <strong>Preço: </strong>
        <%= l.price %>
    </div>
    <%= link_to 'detalhes', lamp_path(l) %>
    </p>

</div>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>
  
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href= "/categories/1"> Luminárias </a></li>
        <li><a href="/categories/2"> Utensílios de cozinha </a></li>
        <li><a href="#"> Brindes para empresas </a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Categorias <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |c| %>
              <li>
                <%= link_to c.name, category_path(c) %>
              </li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="#"> Cursos </a></li>
          </ul>
        </li>
      </ul>
      
      <%= render 'layouts/search' %>
      <%= render 'layouts/user' %>
        
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_search.html.erb
<form class="navbar-form navbar-left">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search"> 
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
          

app/views/layouts/_sidebar_yield.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-2">
      <ul class="nav nav-pills nav-stacked">
        <% Category.all.each do |c| %>
          <li>
            <%= link_to c.name, category_path(c) %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-xs-10">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      <%= yield %>
      
    </div>
  </div>
</div>  
    

app/views/layouts/_user.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %> 
    <ul> 
      <li><a href="/user"><%= current_user.email %></a></li> 
      <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li> 
    </ul> 
  <% else %> 
    <ul> 
      <li><%= link_to "Entrar", '/users/sign_in' %></a></li> 
      <li><%= link_to "Cadastrar", '/users/sign_up' %></a></li> 
    </ul> 
  <% end %>
</ul>
<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="/orders/cart" class="show-cart">Meu carrinho</a></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>NunesBambuWebpage</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/ffaba34bad.js"></script>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="logo">
      <%= image_tag("logo/nunes_bambu_teste.jpg")  %> 
    </div>
    
    <%= render 'layouts/navbar' %>
    <div class="cart-container"></div>
    <%= render 'layouts/sidebar_yield' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    
  </body>
  
</html>